version: '3.8'

services:
  php:
    container_name: php-dev
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www/html

  app:
    container_name: nginx
    image: nginx:1.27.0-alpine
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    restart: always

  node:
    container_name: node-dev
    image: node:22-alpine
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - ./app:/var/www/html

  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "base"
    volumes:
      - ./docker/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9090:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

  redis:
    container_name: cache
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass "root"
    volumes:
      - ./docker/redis:/data
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD="root"

  redisinsight:
    container_name: cache-view
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - ./docker/redisinsight:/data